### ISSUE TITLE
无法登陆和注册！

### ISSUE THREAD

**Issue by zhi3210happy** [luckcoding/hotchcms#3]
xhr.js?21f6:178 OPTIONS http://localhost:3030/api/admin-account net::ERR_CONNECTION_REFUSED

**Comment by luckcoding** [comment]
@zhi3210happy hi，已增加安装模块，具体步骤可以参考 README.md。
如果解决不了，麻烦贴下具体的问题

**Comment by markma98** [comment]
对backstage编译(npm run build)时出错：

./src/components/DataTable/DataTable.js
Module build failed: TypeError: D:\mydocknowledge\webb\node.js\koa2\githubprjs\hotchcms-master\backstage\src\components\DataTable\DataTable.js: Duplicate declaration "React"
> 1 | import React from 'react'

thanks.
