### ISSUE TITLE
backstage编译(npm run build)时出错

### ISSUE THREAD

**Issue by markma98** [luckcoding/hotchcms#4]
对backstage编译(npm run build)时出错：

./src/components/DataTable/DataTable.js
Module build failed: TypeError: \hotchcms-master\backstage\src\components\DataTable\DataTable.js: Duplicate declaration "React"

1 | import React from 'react'

thanks.

**Comment by luckcoding** [comment]
@markma98 如果方便，请贴一下编译环境
