### ISSUE TITLE
后台代码启动报错

### ISSUE THREAD

**Issue by Hyg900928** [luckcoding/hotchcms#6]
![image](https://user-images.githubusercontent.com/19190553/50201411-f3182600-0394-11e9-80a2-69d5fa6ca141.png)

**Comment by luckcoding** [comment]
@Hyg900928 是哪一步执行报错的？

**Comment by Hyg900928** [comment]
是后端代码 ， 在执行npm run dev的时候报错的， 后来我找出错误所在了。开始的时候 ，我是用yarn 来安装包的， 在安装koa-authority 的时候， 提示我没有v1.1.0 版本的。 后来我重新使用npm 来安装包，这个错误就没有了

**Comment by Hyg900928** [comment]
感谢题主回答
