### ISSUE TITLE
后台执行安装模块的时候 ，报错

### ISSUE THREAD

**Issue by Hyg900928** [luckcoding/hotchcms#7]
![image](https://user-images.githubusercontent.com/19190553/50201959-383d5780-0397-11e9-8b67-ced0218251a1.png)

**Comment by Hyg900928** [comment]
这个是怎么回事呢

**Comment by luckcoding** [comment]
@Hyg900928 已更新。

此后将开启多个分支进行开发，以保证master分支可正常启用。 #8

**Comment by Hyg900928** [comment]
@luckcoding 感谢分享，我会一直跟下去的

**Comment by Hyg900928** [comment]
我更新后，又报了这个错误，麻烦给看一下了

![image](https://user-images.githubusercontent.com/19190553/50207043-46e03a80-03a8-11e9-863b-4219870500ee.png)

**Comment by luckcoding** [comment]
执行 init 必须先启动项目。

1. 启动项目 `npm start` or `npm run dev`
2. 初始化安装 `npm init`

**Comment by Hyg900928** [comment]
@luckcoding 这次解决了， 感谢

**Comment by Hyg900928** [comment]
题主， 有时间，能完善一下文档就完美了

**Comment by luckcoding** [comment]
@Hyg900928 ths for you star
文档会尽快完成。这个issue就先关闭了，如果有问题，可以再次打开。

**Comment by Hyg900928** [comment]
嗯嗯 ，
