### ISSUE TITLE
后端代码 执行npm run init 报这个错误

### ISSUE THREAD

**Issue by Hyg900928** [luckcoding/hotchcms#9]
![image](https://user-images.githubusercontent.com/19190553/50207375-4300e800-03a9-11e9-8715-3592a5364811.png)

**Comment by Hyg900928** [comment]
![image](https://user-images.githubusercontent.com/19190553/50207398-58761200-03a9-11e9-9ee8-6aef81bbddea.png)
执行到这里出毛病了

**Comment by Hyg900928** [comment]
解决了，感谢

**Comment by luckcoding** [comment]
#7
